// Generated by https://quicktype.io

export interface User2 {
  mensaje:                null;
  estaAutenticado:        boolean;
  userName:               string;
  email:                  string;
  roles:                  string[];
  token:                  string;
  refreshToken:           string;
  refreshTokenExpiration: Date;
}
